# standard library modules / datetime / strftime
import datetime
print(datetime.datetime.now())
print(datetime.datetime.today())
print(datetime.datetime(year=1990, month=9, day=2, hour=4, minute=12, second=32))
str_format_datetime = datetime.datetime.now()
print(str_format_datetime.strftime("%a"))
print(str_format_datetime.strftime("%A"))
print(str_format_datetime.strftime("%w"))
print(str_format_datetime.strftime("%d"))
print(str_format_datetime.strftime("%b"))
print(str_format_datetime.strftime("%B"))
print(str_format_datetime.strftime("%m"))
print(str_format_datetime.strftime("%y"))
print(str_format_datetime.strftime("%Y"))
print(str_format_datetime.strftime("%H"))
print(str_format_datetime.strftime("%H"))
print(str_format_datetime.strftime("%h"))
print(str_format_datetime.strftime("%I"))
print(str_format_datetime.strftime("%p"))
print(str_format_datetime.strftime("%M"))
print(str_format_datetime.strftime("%S"))
print(str_format_datetime.strftime("%C"))
