# string methods
string_object = 'string'
print(string_object.index('t'))
print(string_object.count('t'))
print(string_object.encode(encoding='utf_8', errors='replace'))
print(string_object.isdigit())
print(string_object.isalpha())
print(string_object.islower())
print(string_object.isdecimal())
print(string_object.istitle())
print(string_object.isnumeric())
print(string_object.isupper())
print(string_object.isspace())
print(string_object.isprintable())
print(string_object.isalnum())
print(string_object.lower())
print(string_object.upper())
print(string_object.capitalize())
print(string_object.title())
print(string_object.find('t'))
print(string_object.startswith('s'))
print(string_object.split('r'))
print(string_object.endswith('e'))
print(string_object[2:])
join_iterable = ('item1', 'item2', 'item3')
print(','.join(join_iterable))
